# -*- coding: utf-8 -*-
"""Core 튜터링 2주차.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17mljQ82q5E1dbscHJkEiMzs7yTmCfPIZ

오늘의 목표
- 백준 15953번 상금 헌터 (카카오 코드 페스티벌 2018 1번 문제) 문제 풀기

오늘 배울 사항
- 파이썬으로 입출력하는 기본적인 방법에 대해 알 수 있다. (input함수 파헤치기)
- 파이썬으로 조건문(if ~ else / if ~ elif ~ else)을 작성할 수 있다.
- 파이썬으로 반복문(for / while)을 작성하고 
  어느 상황에 for문을 쓰는지, 어느 상황에 while문을 쓰는 것이 좋은지 말할 수 있다. 
  (면접 "기본" 문제 - "기본기의 중요성"이죠. 그러나 뚜렷한 정답은 없습니다.
   자기 생각/경험을 어떻게 잘 말하는지가 핵심!)
- 파이썬으로 리스트를 작성해보고 왜 리스트를 써야 하는지 말할 수 있다.

기본기 다지기
- 백준 1000번 A + B       : int를 2개 받는 방법
- 백준 1330번 두 수 비교하기    : if ~ elif ~ else문 사용해 보기
- 백준 8393번 합         : for문 사용해보기 / for문을 안쓰고 푸는 방법?
- 백준 10952 A+B - 5      : while문 사용해보기
- 백준 10871 X보다 작은 수       : 리스트 사용해보기

실전 문제
- 백준 14681 사분면 고르기 (Canadian Computing Competition > 2017 Junior Division 1번 문제)
- 백준 8958 OX퀴즈 (ICPC > Asia Regional > Seoul 2005 > A번 문제)
- 백준 2577 숫자의 개수 (한국정보올림피아드 > 지역본선 2006 > 초등부 2번 문제)
- 백준 15953 상금 헌터 (카카오 코드 페스티벌 2018 > 1번 문제)

백준 8393번 : 합
"""

# n이 주어졌을 때, 1부터 n까지 합을 구하는 프로그램을 작성하시오.
# for문 사용
a = int(input())
sum = 0
for i in range (1,a+1):
  sum += i
print(sum)

# n이 주어졌을 때, 1부터 n까지 합을 구하는 프로그램을 작성하시오.
# 다른방법사용
a = int(input())
sum = a * (a+1)/2  # 수학에서 합 구하는 공식
print(int(sum))    # 강제 형변환 : 컴츄터가 임의로 형을 바꿨을 때 사용자가 원하는 형으로 바꾸는 것

"""백준 1000번 A + B"""

# 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.
A,B = map(int,input().split(' '))
print(A + B)

# 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오. (방법 2)

l = [int(x) for x in input().split()]
sum = 0
for x in l:
  sum += x

print(sum)

print(l)

"""백준 1330번 두 수 비교하기"""

# 두 정수 A와 B가 주어졌을 때, A와 B를 비교하는 프로그램을 작성하시오. (if-elif-else 문)
a,b = map(int,input().split(' '))
if a > b :
  print('>')
elif a < b :
  print('<')
else :
  print('==')

a,b = map(int,input().split(' '))
if a > b :
  print('>')
elif a < b :
  print('<')
else :
  print('==')

a,b = map(int,input().split(' '))
if a > b :
  print('>')
elif a < b :
  print('<')
else :
  print('==')

"""백준 15953번 상금헌터 (카카오 코드 페스티벌 2018 1번 문제)"""

T = int(input())
for i in range(0,T,1):
  a,b = map(int,input().split(' '))
  
  sum = 0
  if a == 0 :
    sum += 0
  elif a == 1:
    sum += 500
  elif a < 4 :
    sum += 300
  elif a < 7 :
    sum += 200
  elif a < 11 :
    sum += 50
  elif a < 16 :
    sum += 30
  elif a < 22 :
    sum += 10
  else :
    sum += 0

  if b == 0 :
    sum += 0
  elif b == 1:
    sum += 512
  elif b < 4 :
    sum += 256
  elif b < 8 :
    sum += 128
  elif b < 16 :
    sum += 64
  elif b < 32 :
    sum += 32
  else :
    sum += 0

  print(sum*10000)

"""백준 10952번 A + B - 5"""

# 두 정수 A와 B를 입력받은 다음, A+B를 출력하는 프로그램을 작성하시오.

while True:  # 무한 루프 (문장이 무조건 참인 조건이어서 while문이 끝나지 않음) 
  A,B = map(int,input().split())
  if A != 0 and B != 0:
    print(A + B)
  else:
    break

