# -*- coding: utf-8 -*-
"""Core 튜터링 3주차.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wASsrafmcmMJUrxC10bBU6xQov57Gw2G

백준 2438 별찍기(1)
"""

a = int(input(''))
for i in range(1,a+1):
  print('*'*i)

"""백준 2439 별찍기(2)"""

a = int(input(''))
for i in range(1,a+1):
  print(' '*(a-i),'*'*i)

a = int(input())
for i in range(1,a+1):
    print(' '*(a-i),end='')
    print('*'*i)

"""백준 1259 팰린드롬수"""

while True:
  a = int(input())

  #리스트 하나 만들기
  lists = []

  #0이면 while문 강제종료
  if a == 0:
    break

  else:
    #팰린드롬수인지 아닌지 판단하는 코드
    counts = 0
    while a != 0:
      b = a % 10   #맨끝자리 수가 나옴
      lists.append(b)   #리스트 안에 끝자리수를 넣는다.
      a = int(a / 10)   # a를 10으로 나누어서 다음 자리 수를 구함
      counts = counts + 1   # counts를 쓴 이유는 a의 자리수를 구하기 위해서

    # print(lists)

    # 맨 앞자리 수와 맨 뒷자리 수가 같은지 판별
    sw = 0
    for i in range(0,int(counts/2),1):
      if lists[i] != lists[counts-1-i]:
        sw = 1
        print('no')
        break
    if sw == 0:
      print('yes')

# 다른 풀이
a = input()
sizes = len(a)

for i in range(0,int(sizes/2),1):
  ...
  ...

"""백준 10988 팬린드롬인지 확인하기"""

a = input()
sizes = int(len(a)/2)

sw = 0
for i in range(0,sizes,1):
  if a[i] != a[len(a)-1-i]:   #i = 0일때 a[0]==a[4]
    print('0')
    sw = 1
    break

if sw == 0:
  print('1')

"""백준 15596 정수 N개의 합"""

# 함수 정의하기
# 함수를 처음에 생성(선언)할 때는 def를 사용한다. (def = definition)
def solve(lists):   # lists : 매개 변수
  # lists 안에 있는 수들의 합
  sum = 0
  for i in lists:
    sum += i

  return sum  #함수를 통해서 구한 값을 밖에 보내는 것을 return 이라고 함

# 함수 사용하기
lists = [1,2,3,4,5,6]
print(solve(lists))

"""백준 2577 숫자의 개수"""

a = int(input())
b = int(input())
c = int(input())

S = a * b * c

lists = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
S_str = str(S)

for i in range(len(S_str)):
  e = int(S_str[i])
  lists[e]=lists[e]+1

print(lists)
for i in lists:
  print(i)

