# -*- coding: utf-8 -*-
"""Core_튜터링_1주차.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J1-RnanP-3ZBD62K_JTxNHT22ewsgdp0

백준 2557 - Hello World
"""

print("Hello World!")

"""백준 10171 - 고양이"""

print("\\    /\\")
print(" )  ( ')")
print("(  /  )")
print(" \\(__)|")